Update CI (1)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -69,32 +69,36 @@ commands:
         type: string
     steps:
       - run:
-          name: Publish artifacts to Sonatype Snapshots
+          name: 'Publish artifacts to Sonatype Snapshots (shaded: << parameters.shaded >>)'
           command: |
                     if [ ! "${CIRCLE_BRANCH}" = "master" ]; then
                       echo "Skipped on branch ${CIRCLE_BRANCH}"
                       exit 0
                     fi
 
-                    V=`sbt 'show version' 2>&1 | sed 's/\x1b\[0[Jm]//g' | grep '[0-9]\+\.[0-9]\+' | tail -1 | sed 's/\[info\]//' | xargs | tr -cd '[:alnum:]._-'`
-
-                    if [ `echo "$V" | grep -- '-SNAPSHOT' | wc -l` -eq 0 ]; then
-                      S=`echo "$V" | perl -pe 's/([0-9]+)$/${\($1 + 1)}-SNAPSHOT/'`
-                      echo "Cannot bump $V to $S"
-                      echo "ThisBuild / version := \"$S\"" > version.sbt
+                    if [ "x$PUBLISH_USER" = "x" -o "x$PUBLISH_PASS" = "x" ]; then
+                      echo "Missing publication credentials"
+                      exit 1
                     fi
 
+                    # Make sure to export variables before the first call to `sbt`
+                    # so that the variable are defined in the SBT server;
+                    # Otherwise `sbt` will then run a client connected to a server
+                    # where the variables defined meanwhile are not available.
                     export REACTIVEMONGO_SHADED="<< parameters.shaded >>"
          
                     export PUBLISH_REPO_NAME="Sonatype Nexus Repository Manager"
                     export PUBLISH_REPO_ID="central.sonatype.com"
                     export PUBLISH_REPO_URL="https://central.sonatype.com/repository/maven-snapshots/"
                     
-                    if [ "x$PUBLISH_USER" = "x" -o "x$PUBLISH_PASS" = "x" ]; then
-                      echo "Missing publication credentials"
-                      exit 1
+                    V=`sbt 'show version' 2>&1 | sed 's/\x1b\[0[Jm]//g' | grep --color=never '[0-9]\+\.[0-9]\+' | tail -1 | sed 's/\[info\]//' | xargs | tr -cd '[:alnum:]._-'`
+
+                    if [ `echo "$V" | grep -- '-SNAPSHOT' | wc -l` -eq 0 ]; then
+                      S=`echo "$V" | perl -pe 's/([0-9]+)$/${\($1 + 1)}-SNAPSHOT/'`
+                      echo "Cannot bump $V to $S"
+                      echo "ThisBuild / version := \"$S\"" > version.sbt
                     fi
-                    
+              
                     sbt "++<< parameters.scala_version >>" publish
 
 jobs:
